### ISSUE TITLE
Incomplete List of Symbols

### ISSUE THREAD

**Issue by StockTrackerJ** [edgedalmacio/phisix#74]
Hi Edge,

I check the "all stock" and individual stock there are missing symbols/stock codes. There about 60-90 missing stocks. Sample here is LBC and FEU. Can you pls. confirm if this is the case? Thanks.

![image](https://user-images.githubusercontent.com/59072791/71559568-8e5cd480-2a9a-11ea-971e-9650d4aaf407.png)
![image](https://user-images.githubusercontent.com/59072791/71559578-b0565700-2a9a-11ea-987c-b4079d229338.png)

**Comment by edgedalmacio** [comment]
There are cases when some stocks do not trade for a day or several days. When that happens, the API will return a `404` for the stocks not trading on that day.

Example:

http://phisix-api.appspot.com/stocks/LBC.2019-12-30.json
- LBC wasn't trading on Dec 30, 2019, that's why you were getting a `404` response.

http://phisix-api.appspot.com/stocks/LBC.2019-01-02.json
- However, if you check LBC for Jan 2, 2020, you would see that it's working as expected.

**Comment by StockTrackerJ** [comment]
HI Edge, 

Thanks for the clarification. Is it to possible to make it still return the last traded price even for days with a trade? Example, let's say Stock A was traded last Jan 2 with price of P10 with volume of 100K, then no trades on succeeding days, let's say Jan 8, it has no trade but when requested (on said date),  will still return a price of P10 with % change of 0 and volume of 0, instead of getting 404 response. Is that possible? Thanks very much for work. Appreciate it a lot.

**Comment by boknoypatotoy** [comment]
I agree with you ... it is better to return the last data instead of removing it from the arrays ...
